2021-03-09 03:13:05,692: Yaha to pahuch gaye beta ji 
2021-03-09 03:15:34,859: C:\Users\Vaishnavi\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 03:15:34,860: C:\Users\Vaishnavi\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 03:15:53,115: Yaha to pahuch gaye beta ji 
2021-03-09 03:16:34,691: C:\Users\Vaishnavi\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 03:16:34,767: C:\Users\Vaishnavi\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 03:16:42,857: Yaha to pahuch gaye beta ji 
2021-03-09 03:16:58,704: C:\Users\Vaishnavi\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 03:16:58,705: C:\Users\Vaishnavi\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 03:17:04,017: Yaha to pahuch gaye beta ji 
2021-03-09 10:42:20,678: Not Found: /favicon.ico 
2021-03-09 10:42:22,187: Not Found: /favicon.ico 
2021-03-09 10:42:26,803: Yaha to pahuch gaye beta ji 
2021-03-09 10:42:33,913: Not Found: /home/audit-log 
2021-03-09 10:42:56,535: Internal Server Error: /audit-log/ 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py", line 1321, in audit_log_view
    return render(request, 'IRP/AuditLog.html')
  File "C:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: IRP/AuditLog.html
2021-03-09 10:43:21,896: C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 10:44:55,553: Internal Server Error: /audit-log/ 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py", line 1321, in audit_log_view
    return render(request, 'AuditLog.html')
  File "C:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: AuditLog.html
2021-03-09 10:45:11,309: C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 10:45:12,999: Internal Server Error: /audit-log/ 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py", line 1321, in audit_log_view
    return render(request, 'IRP/AuditLog.html')
  File "C:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: IRP/AuditLog.html
2021-03-09 10:45:53,833: C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 10:45:55,858: Internal Server Error: /audit-log/ 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py", line 1321, in audit_log_view
    return render(request, 'AuditLog.html')
  File "C:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: AuditLog.html
2021-03-09 10:45:57,049: Internal Server Error: /audit-log/ 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py", line 1321, in audit_log_view
    return render(request, 'AuditLog.html')
  File "C:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: AuditLog.html
2021-03-09 10:46:06,392: C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 10:46:08,240: Internal Server Error: /audit-log/ 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py", line 1321, in audit_log_view
    return render(request, '/AuditLog.html')
  File "C:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /AuditLog.html
2021-03-09 10:47:07,890: C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 10:47:18,742: Internal Server Error: /audit-log/ 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py", line 1321, in audit_log_view
    return render(request, '/IRP/AuditLog.html')
  File "C:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /IRP/AuditLog.html
2021-03-09 10:50:34,139: C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 10:58:04,183: C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
2021-03-09 10:58:39,096: C:\Users\pulkit.bajaj\Documents\GitHub\IRP\IRP\Incedoinc\views.py changed, reloading. 
